services:
  - type: web
    name: turnbase
    runtime: node
    buildCommand: npm install
    startCommand: npx tsx --env-file=/etc/secrets/env src/index.ts
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
